config/routes.rb
Rails.application.routes.draw do
  resources :check_links

  root 'welcome#index'

end

app/models/check_link.rb
require 'rubygems'
require 'nokogiri'
require 'rest_client'
require "set"
require 'typhoeus'

class CheckLink < ActiveRecord::Base
  validates :checked_url, presence: true
	
	
	def initialize()
		#in rails when you need to use your own initialize you need to use super
		super
		@links_hash = Hash.new
		@links_visited = Hash.new
		@error_links = Hash.new
		@link_stack = Array.new
		@end_flag = false
		@hostname = ''
	end

    
  def get_all_links(model_check_link)
    #Get only the hostname to compare afterwards
    @hostname = get_host_without_www(model_check_link)
    
    
    #Get links for the first page
    links = get_links_for_single_link(model_check_link)
    links.each do |link1|
      #Ignore the link if https
      if link1.include? 'https' or link1.include? 'jpg' or link1.include? 'gif' or link1.include? 'mailto'
          next
      end
      
      #if link starts with / then append hostname
      if link1.start_with? '/'
          link1 = 'http://www.' + @hostname + link1
      end 
      
      if @links_hash.key?(link1)
        @links_hash[link1] += 1
      else
        @links_hash[link1] = 1
        #Put all the domain matching links on the stack
        if get_host_without_www(link1) == @hostname
          @link_stack.push(link1)
        end  
      end
    end
    puts @links_hash.length 
    puts @link_stack.length
    
    
    #Loop through the stack until the stack is empty to get all the links 
    #that needs to be visited
    until @link_stack.empty?
      puts @link_stack.length
      new_link = @link_stack.pop()
      puts new_link
      if new_link.start_with? '/'
        new_link = 'http://www.' + @hostname + new_link
      end
      
      links = get_links_for_single_link(new_link)
      links.each do |link2|
        if link2.include? 'https' or link2.include? 'jpg' or link2.include? 'gif' or link2.include? 'mailto'
          next
        end
        if link2.start_with? '/'
            link2 = 'http://www.' + @hostname + link2
        end
        
        if @links_hash.key?(link2)
          @links_hash[link2] += 1
        else
          @links_hash[link2] = 1
          #Put all the domain matching links on the stack
          if get_host_without_www(link2) == @hostname
            @link_stack.push(link2)
          end
        end  
      end
    end
      
  puts @links_hash.length     
  puts @link_stack.length
  
  start_checking()
  puts @error_links.length
  
  @error_links.each do |key,value|
    puts key
  end
  
  self.errors_found = @error_links.length
  self.checked_url = model_check_link
  
  end
  
  
	private
		def get_links_for_single_link(link)
		  begin
		    res = RestClient.get(link)
		    page = Nokogiri::HTML(res) 
        links = page.css("a")
        hrefs = links.map {|link3| link3.attribute('href').to_s}.uniq.sort.delete_if {|href| href.empty?}
        return hrefs
      rescue
          @error_links[link] = '800'
          return []
		  end
		end

		def get_host_without_www(url)
		  begin
		    uri = URI.parse(url)
        uri = URI.parse("http://#{url}") if uri.scheme.nil?
        host = uri.host.downcase
        host.start_with?('www.') ? host[4..-1] : host
      rescue
        return 'false'
		  end
		end
		
		def start_checking()
		  hydra = Typhoeus::Hydra.new
		  successes = 0
		  fail = 0
		  @links_hash.each do |url,value|
        request = Typhoeus::Request.new(url,followlocation: true)
        request.on_complete do |response|
           if response.success?
               successes += 1
           elsif response.timed_out?
               # aw hell no
               puts "got a time out"
           elsif response.code == 0
               # Could not get an http response, something's wrong.
               puts response.return_message
           else
               @error_links[url] = response.code
           end
          end
        hydra.queue(request)
		  end
		  puts 'Started running'
		  hydra.run 
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/check_links_controller.rb
class CheckLinksController < ApplicationController
  before_action :set_check_link, only: [:show, :edit, :update, :destroy]

  # GET /check_links
  # GET /check_links.json
  def index
    @check_links = CheckLink.all
  end

  # GET /check_links/1
  # GET /check_links/1.json
  def show
  end

  # GET /check_links/new
  def new
    puts 'In nes'
    @check_link = CheckLink.new()
  end

  # GET /check_links/1/edit
  def edit
  end

  # POST /check_links
  # POST /check_links.json
  def create
    @check_link = CheckLink.new()

    @check_link.get_all_links(check_link_params['checked_url'])
    respond_to do |format|
      if @check_link.save
        format.html { redirect_to @check_link, notice: 'Check link was successfully created.' }
        format.json { render :show, status: :created, location: @check_link }
      else
        format.html { render :new }
        format.json { render json: @check_link.errors, status: :unprocessable_entity }
      end
    end
  end
 
=begin
  def create
    @check_link = CheckLink.new()

    #@check_link.get_all_links(check_link_params['checked_url'])
    response.headers['Content-Type'] = 'text/event-stream'
    response.stream.write(@check_link.stream)
    respond_to do |format|
      if @check_link.save
        #@check_link.get_all_links(check_link_params['checked_url'])
        
        #response.stream.write(@check_link.stream)
        format.html { redirect_to @check_link, notice: 'Check link was successfully created.' }
        format.json { render :show, status: :created, location: @check_link }
      else
        format.html { render :new }
        format.json { render json: @check_link.errors, status: :unprocessable_entity }
      end
    end
    
    ensure
      response.stream.close
    
  end
=end

 
  # PATCH/PUT /check_links/1
  # PATCH/PUT /check_links/1.json
  def update
    respond_to do |format|
      if @check_link.update(check_link_params)
        format.html { redirect_to @check_link, notice: 'Check link was successfully updated.' }
        format.json { render :show, status: :ok, location: @check_link }
      else
        format.html { render :edit }
        format.json { render json: @check_link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /check_links/1
  # DELETE /check_links/1.json
  def destroy
    @check_link.destroy
    respond_to do |format|
      format.html { redirect_to check_links_url, notice: 'Check link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_check_link
      @check_link = CheckLink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def check_link_params
      params.require(:check_link).permit(:checked_url, :errors_found)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/check_links_helper.rb
module CheckLinksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/check_links/_form.html.erb
<%= form_for(@check_link) do |f| %>
  <% if @check_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check_link.errors.count, "error") %> prohibited this check_link from being saved:</h2>

      <ul>
      <% @check_link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :checked_url %><br>
    <%= f.text_area :checked_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/check_links/edit.html.erb
<h1>Editing Check Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @check_link %> |
<%= link_to 'Back', check_links_path %>

app/views/check_links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Check Links</h1>

<table>
  <thead>
    <tr>
      <th>Checked url</th>
      <th>Errors found</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @check_links.each do |check_link| %>
      <tr>
        <td><%= check_link.checked_url %></td>
        <td><%= check_link.errors_found %></td>
        <td><%= link_to 'Show', check_link %></td>
        <td><%= link_to 'Edit', edit_check_link_path(check_link) %></td>
        <td><%= link_to 'Destroy', check_link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Check link', new_check_link_path %>

app/views/check_links/new.html.erb
<h1>New Check Link</h1>

<%= render 'form' %>

<%= link_to 'Back', check_links_path %>

app/views/check_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Checked url:</strong>
  <%= @check_link.checked_url %>
</p>

<p>
  <strong>Errors found:</strong>
  <%= @check_link.errors_found %>
</p>

<%= link_to 'Edit', edit_check_link_path(@check_link) %> |
<%= link_to 'Back', check_links_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinksCheck</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>